if(EXISTS "/home/z/work/hanzo/yoga/build-clang21-libcxx/tests/yogatests[1]_tests.cmake")
  include("/home/z/work/hanzo/yoga/build-clang21-libcxx/tests/yogatests[1]_tests.cmake")
else()
  add_test(yogatests_NOT_BUILT yogatests_NOT_BUILT)
endif()
